// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.flipkart.gojira.sample.app.grpc;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_flipkart_gojira_sample_app_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_flipkart_gojira_sample_app_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_flipkart_gojira_sample_app_grpc_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_flipkart_gojira_sample_app_grpc_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022#com.flipkart.gojira." +
      "sample.app.grpc\"\034\n\014HelloRequest\022\014\n\004name\030" +
      "\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t2{\n\007" +
      "Greeter\022p\n\010SayHello\0221.com.flipkart.gojir" +
      "a.sample.app.grpc.HelloRequest\032/.com.fli" +
      "pkart.gojira.sample.app.grpc.HelloReply\"" +
      "\000B>\n#com.flipkart.gojira.sample.app.grpc" +
      "B\017HelloWorldProtoP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_flipkart_gojira_sample_app_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_flipkart_gojira_sample_app_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_flipkart_gojira_sample_app_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_flipkart_gojira_sample_app_grpc_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_flipkart_gojira_sample_app_grpc_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_flipkart_gojira_sample_app_grpc_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
